In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.0.1+cu118


In [2]:
#Creating Tensors
#scalar
scalar=torch.tensor(7)
scalar

tensor(7)

In [3]:
scalar.ndim

0

In [4]:
#get int from tensor
scalar.item()

7

In [5]:
vector=torch.tensor([7,7])
vector

tensor([7, 7])

In [6]:
vector.shape

torch.Size([2])

In [7]:
vector.ndim

1

In [8]:
#MATRIX
MATRIX=torch.tensor([[7,8],
        [9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [9]:
MATRIX.ndim

2

In [10]:
MATRIX.shape

torch.Size([2, 2])

In [11]:
MATRIX[0],MATRIX[1]

(tensor([7, 8]), tensor([ 9, 10]))

In [12]:
#TENSOR
TENSOR=torch.tensor([[[1,2,3],
                     [3,6,9],
                     [2,4,5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [13]:
TENSOR.ndim

3

In [14]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

In [15]:
#Random tensors
random_tensor=torch.rand(1,3,4)
random_tensor

tensor([[[0.2514, 0.9168, 0.3774, 0.6987],
         [0.4570, 0.4052, 0.0894, 0.7724],
         [0.7845, 0.0815, 0.4613, 0.3401]]])

In [16]:
random_tensor.ndim

3

In [17]:
random_tensor.shape

torch.Size([1, 3, 4])

In [18]:
random_image_size_tensor=torch.rand(size=(224,224,3))
random_image_size_tensor

tensor([[[0.9107, 0.4493, 0.5987],
         [0.7644, 0.2665, 0.7095],
         [0.0485, 0.5801, 0.6045],
         ...,
         [0.9864, 0.4288, 0.5850],
         [0.2172, 0.3227, 0.1408],
         [0.6047, 0.4403, 0.0477]],

        [[0.5578, 0.1235, 0.9861],
         [0.7975, 0.4506, 0.5927],
         [0.4519, 0.1743, 0.7638],
         ...,
         [0.6116, 0.9249, 0.5979],
         [0.1111, 0.1278, 0.9178],
         [0.2170, 0.9852, 0.3161]],

        [[0.7840, 0.7154, 0.0514],
         [0.5503, 0.2855, 0.2446],
         [0.6676, 0.7593, 0.7038],
         ...,
         [0.7928, 0.2790, 0.6557],
         [0.3962, 0.6707, 0.6995],
         [0.6427, 0.5034, 0.8771]],

        ...,

        [[0.3920, 0.4026, 0.3470],
         [0.0039, 0.8052, 0.2308],
         [0.9481, 0.1948, 0.0097],
         ...,
         [0.5123, 0.8722, 0.2960],
         [0.1723, 0.5796, 0.3081],
         [0.7631, 0.2858, 0.0329]],

        [[0.0266, 0.3091, 0.0984],
         [0.6239, 0.9153, 0.7345],
         [0.

In [19]:
random_image_size_tensor.ndim

3

In [20]:
#zeros and ones
zeros=torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [21]:
ones=torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [22]:
ones.dtype

torch.float32

In [23]:
one_to_ten=torch.arange(1,11)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [24]:
#creating tensor like
ten_zeros=torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [25]:
#Tensor Datatypes
#float32 tensor
float_32_tensor=torch.tensor([3.0,6.0,9.0],dtype=None)
float_32_tensor

tensor([3., 6., 9.])

In [26]:
float_32_tensor.dtype

torch.float32

In [27]:
float_16_tensor=torch.tensor([3.0,6.0,9.0],dtype=torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [28]:
float_16_tensor.dtype

torch.float16

In [29]:
float_16_tensor=float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [30]:
(float_16_tensor*float_32_tensor).dtype

torch.float32

In [31]:
int_32_tensor=torch.tensor([3,6,9],dtype=torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [32]:
int_long_tensor=torch.tensor([3,6,9],dtype=torch.long)
int_long_tensor

tensor([3, 6, 9])

In [33]:
float_32_tensor*int_32_tensor

tensor([ 9., 36., 81.])

In [34]:
some_tensor=torch.rand(3,4)
some_tensor

tensor([[0.3292, 0.7806, 0.3114, 0.8914],
        [0.9393, 0.5325, 0.7883, 0.7918],
        [0.5925, 0.3561, 0.4514, 0.7302]])

In [35]:
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.size()}")
print(f"Device the tensor is on: {some_tensor.device}")

tensor([[0.3292, 0.7806, 0.3114, 0.8914],
        [0.9393, 0.5325, 0.7883, 0.7918],
        [0.5925, 0.3561, 0.4514, 0.7302]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device the tensor is on: cpu


In [36]:
#manipulating tensors(tensor operations)
tensor=torch.tensor([1,2,3])
tensor+10,tensor-10,tensor*10,tensor/2

(tensor([11, 12, 13]),
 tensor([-9, -8, -7]),
 tensor([10, 20, 30]),
 tensor([0.5000, 1.0000, 1.5000]))

In [37]:
#You can also pytorch in built functions
torch.mul(tensor,10),torch.add(tensor,10)

(tensor([10, 20, 30]), tensor([11, 12, 13]))

In [38]:
#element wise multiplication
print(f"{tensor} * {tensor} = {tensor*tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3]) = tensor([1, 4, 9])


In [39]:
#matrix multiplication
torch.matmul(tensor,tensor)

tensor(14)

In [40]:
%%time
value=0
for i in range(len(tensor)):
  value+=tensor[i]*tensor[i]
print(value)

tensor(14)
CPU times: user 985 µs, sys: 0 ns, total: 985 µs
Wall time: 1.04 ms


In [41]:
%%time
torch.matmul(tensor,tensor)

CPU times: user 34 µs, sys: 0 ns, total: 34 µs
Wall time: 37.4 µs


tensor(14)

In [42]:
torch.matmul(torch.rand(2,3),torch.rand(3,2))

tensor([[0.4156, 0.2982],
        [0.2958, 0.3203]])

In [43]:
#Shapes for matrix mulitplications
tensor_A=torch.tensor([[1,2],
                       [3,4],
                       [5,6]])
tensor_B=torch.tensor([[7,10],
                       [8,11],
                       [9,12]])

In [44]:
#tranpsose
tensor_B.T,tensor_B.T.shape

(tensor([[ 7,  8,  9],
         [10, 11, 12]]),
 torch.Size([2, 3]))

In [45]:
tensor_B,tensor_B.shape

(tensor([[ 7, 10],
         [ 8, 11],
         [ 9, 12]]),
 torch.Size([3, 2]))

In [46]:
torch.matmul(tensor_A,tensor_B.T)

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

In [47]:
#the matrix mulitplication works when tensor B is transposed
print(f"Original shape:tensor_A={tensor_A.shape} , tensor_B={tensor_B.shape}")
print(f"New shapes:tensor_A={tensor_A.shape} , tensor_B={tensor_B.T.shape}")
print(f"Multiplying: {tensor_A.shape} & {tensor_B.T.shape} <-innrer dimensions must match")
output=torch.matmul(tensor_A,tensor_B.T)
print(f"Output:\n{output}")
print(f"Shape:{output.shape}")

Original shape:tensor_A=torch.Size([3, 2]) , tensor_B=torch.Size([3, 2])
New shapes:tensor_A=torch.Size([3, 2]) , tensor_B=torch.Size([2, 3])
Multiplying: torch.Size([3, 2]) & torch.Size([2, 3]) <-innrer dimensions must match
Output:
tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])
Shape:torch.Size([3, 3])


In [48]:
#Tensor aggreagation
x=torch.arange(0,100,10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [49]:
#find the min
torch.min(x),x.min()

(tensor(0), tensor(0))

In [50]:
#find the max
torch.max(x),x.max()

(tensor(90), tensor(90))

In [51]:
#find the mean
torch.mean(x.type(torch.float32)),x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [52]:
#find the sum
torch.sum(x),x.sum()

(tensor(450), tensor(450))

In [53]:
#positional min and max
x.argmax(),x.argmin()

(tensor(9), tensor(0))

In [54]:
#reshaping,stacking,squeezing and unseqeezing tensors
import torch
x=torch.arange(1.,10.)

In [55]:
x,x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [56]:
#add extra dimension
x_reshaped=x.reshape(1,9)
x_reshaped,x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [57]:
#change the view
z=x.view(1,9)
z,z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [58]:
#view shares memory with original tensor
z[:,0]=5
z,x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [59]:
#stack tensors on top of each other
x_stacked=torch.stack([x,x,x,x])
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [60]:
x_stacked=torch.stack([x,x,x,x],axis=1)
x_stacked

tensor([[5., 5., 5., 5.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])

In [61]:
#torch.sqeeuze() and torch.unsqueeze()
x_reshaped,x_reshaped.squeeze()

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [62]:
x_reshaped.shape,x_reshaped.squeeze().shape

(torch.Size([1, 9]), torch.Size([9]))

In [63]:
print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")

#remove extra dimensions from x_reshaped
x_squeezed=x_reshaped.squeeze()
print(f"\nNew Tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")

Previous tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
Previous shape: torch.Size([1, 9])

New Tensor: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
New shape: torch.Size([9])


In [64]:
print(f"\nPrevious Tensor: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

#add an extra dimension with unsqueeze
x_unsqueezed=x_squeezed.unsqueeze(dim=0)
print(f"\nNew Tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")


Previous Tensor: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
Previous shape: torch.Size([9])

New Tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
New shape: torch.Size([1, 9])


In [65]:
#torch.permute
x_original=torch.rand(size=(224,224,3))
x_permuted=x_original.permute(2,0,1)
x_original.shape,x_permuted.shape

(torch.Size([224, 224, 3]), torch.Size([3, 224, 224]))

In [66]:
#indexing selecting data from tensors
import torch
x=torch.arange(1,10).reshape(1,3,3)
x

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [67]:
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [68]:
#index on 2nd dimension
x[0][0]

tensor([1, 2, 3])

In [69]:
#indexing in the most inner dimension or last dimension
x[0][1][1]

tensor(5)

In [70]:
#You can use ":" to select "all" of a target dimension
x[:,:,1]

tensor([[2, 5, 8]])

In [71]:
#Pytorch and numpy
import torch
import numpy as np
array=np.arange(1.0,8.0)
tensor=torch.from_numpy(array)
array,tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [72]:
#what happens if we change the value of original array?
array=array+1
array,tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [73]:
#tensor to numpy
tensor=torch.ones(7)
numpy_tensor=tensor.numpy()
tensor,numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [74]:
import torch

#create two random tensors
random_tensor_A=torch.rand(3,4)
random_tensor_B=torch.rand(3,4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A==random_tensor_B)

tensor([[0.1224, 0.4379, 0.1247, 0.0896],
        [0.0856, 0.3614, 0.8811, 0.2716],
        [0.1310, 0.8184, 0.9524, 0.8240]])
tensor([[0.3566, 0.1008, 0.2619, 0.0591],
        [0.3409, 0.0047, 0.3959, 0.9699],
        [0.1502, 0.9058, 0.9465, 0.8694]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [75]:
#random reproducible tensors
import torch
torch.manual_seed(42)

random_tensor_C=torch.rand(3,4)
random_tensor_D=torch.rand(3,4)

print(random_tensor_C)
print(random_tensor_C)
print(random_tensor_C==random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [76]:
import torch
torch.manual_seed(42)

random_tensor_C=torch.rand(3,4)

torch.manual_seed(42)
random_tensor_D=torch.rand(3,4)

print(random_tensor_C)
print(random_tensor_C)
print(random_tensor_C==random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


In [77]:
#Running tensors and pytorch objects on the GPUs
#getting a GPU
#Easiest-Use google colab for a free GPU(options to upgrade as well)
#Use your own GPU
#Use cloud computing,these services allow you to rent computers on the cloud

In [78]:
#check for GPU access in pytorch
import torch
torch.cuda.is_available()

True

In [79]:
#setup device agnostic code
device="cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [80]:
#Count number of devices
torch.cuda.device_count()

1

In [81]:
#putting a tensor and models on the GPU
tensor=torch.tensor([1,2,3],device="cpu")

#Tensor not on GPU

print(tensor,tensor.device)

tensor([1, 2, 3]) cpu


In [82]:
#Move tensor to GPU (if available)
tensor_on_gpu=tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

In [83]:
#Moving tensors back to GPU,if tensor is in GPU it cannot be transformed to numpy
tensor_back_to_cpu=tensor_on_gpu.cpu()
tensor_back_to_cpu

tensor([1, 2, 3])

In [84]:
tensor_back_to_cpu=tensor_back_to_cpu.numpy()
tensor_back_to_cpu

array([1, 2, 3])